Update collection.component.jsx
You need to update import from "collection-item.component" to "collection-item.container" to avoid `TypeError: addItem is not a function`